### PR TITLE
Added Pharos Pro to the Tool

### PR DESCRIPTION
**Pull request by PharosVip**

### CODE REVIEW

**Comment by kslr** [comment]
https://itunes.apple.com/app/pharos-pro/id1456610173?ls=1&mt=8 404

**Comment by PharosVip** [comment]
> https://itunes.apple.com/app/pharos-pro/id1456610173?ls=1&mt=8 404
> 
> Android must be published on Google Play.
> All at least 1000 installations

see https://itunes.apple.com/app/pharos-pro/id1456610173&mt=8

**Comment by kslr** [comment]
Use the privacy window to check

PharosVip <notifications@github.com> 于 2019年5月17日周五 07:50写道：

**Comment by PharosVip** [comment]
Sorry, I can't understand what you mean.Could you give me more information?

**Comment by kslr** [comment]
This link is still 404,
have you confirmed that it has been push?

PharosVip <notifications@github.com> 于 2019年5月17日周五 09:16写道：

**Comment by PharosVip** [comment]
It’s a bug of AppStore,you can search Pharos Pro in your appstore.

**Comment by PharosVip** [comment]
Fixed the 404 link

**Comment by PharosVip** [comment]
> This link is still 404, have you confirmed that it has been push? PharosVip <notifications@github.com> 于 2019年5月17日周五 09:16写道：
> […](#)

Fixed the 404 link

**Comment by kslr** [comment]
1. not found
2. merge your commit
3. cancel changes https://github.com/v2ray/manual/pull/265/files#diff-26ce0edcc7b3ecb9bc3fb5261461e0c0L89
4. cancel android icon

**Pull request closed without merging**
