### PR TITLE
Update tool list :Added Pharos Pro Android 

### PR DESCRIPTION
**Pull request by PharosVip**
https://github.com/PharosVip/Pharos-Android-Test

### CODE REVIEW

**Comment by kslr** [comment]
ref #266 

> After serious discussion, we cautiously decided to pause all new listing request regarding _non-free tools, third-party services, or any other change requests to the official website which may either security-related or commercial-related. Unfortunately, it seems your pull request fits both restrictions. We may notify you if there's any change about our merging policy. Yet, I am going to close this pull request. Sorry for the inconvenience.

**Comment by PharosVip** [comment]
It’s free on android.

**Comment by kslr** [comment]
If it is android, please post to Google Play Store.

**Comment by PharosVip** [comment]
It seems fine on github, more than 600 stars.

**Comment by kslr** [comment]
But it is a binary file.

**Comment by PharosVip** [comment]
So what  should I do?

**Comment by kslr** [comment]
It must be reviewed by google play or open source.

**Comment by PharosVip** [comment]
Got it.

**Comment by joshua311** [comment]
How can I get configuration file for android I want it please I want to enjoy internet someone to help me ???

**Pull request closed without merging**
